name: upload_snow_attachment
description: Upload Attachment to ServiceNow
author: bwhitehead0
inputs:
  snow_url:
    description: ServiceNow URL (e.g., https://my-company.service-now.com)
    required: true
  snow_user:
    description: ServiceNow username (Username + password or token are required)
    required: true
  snow_password:
    description: ServiceNow password (Username + password or token are required)
    required: true
  snow_client_id:
    description: "ServiceNow Client ID for oAuth Token auth (Required: User + pass + client ID + client secret)"
    required: false
  snow_client_secret:
    description: "ServiceNow Client Secret for oAuth Token auth (Required: User + pass + client ID + client secret)"
    required: false
  snow_record_sys_id:
    description: ServiceNow Record sys_id
    required: true
  upload_file:
    description: Path to the file to upload
    required: true
  debug:
    description: Enable debug output
    required: false
    default: "false"
  snow_timeout:
    description: "Timeout for ServiceNow API call (default: 60)"
    required: false
    default: "60"
outputs:
  response:
    description: The full JSON response from the ServiceNow API
    value: ${{ steps.upload_snow_attachment.outputs.response }}
runs:
  using: composite
  steps:
    - name: Upload Attachment to ServiceNow
      id: upload_snow_attachment
      shell: bash
      run: |
        response=$(${{ github.action_path }}/assets/upload_snow_attachment.sh \
          -r "${{ inputs.snow_record_sys_id }}" \
          -l "${{ inputs.snow_url }}" \
          -u "${{ inputs.snow_user }}" \
          -p "${{ inputs.snow_password }}" \
          -C "${{ inputs.snow_client_id }}" \
          -S "${{ inputs.snow_client_secret }}" \
          -t "${{ inputs.snow_timeout }}" \
          -D "${{ inputs.debug }}" \
          -f "${{ inputs.upload_file }}" \
          -r "${{ inputs.snow_record_sys_id}}")
        
        if [ "${{ inputs.debug }}" = "true" ]; then
          printf '%s' "API response: $response"
        fi

        echo -E "api_response=$response" >> $GITHUB_OUTPUT

branding:
  icon: "cloud-snow"
  color: "orange"